root: ./

structure:  
  readme: README.md  
  summary: SUMMARY.md
    
redirects:  
  /en/latest: ./README.md
  /en/latest/: ./README.md
  /en/latest/live-player: ./player/live.md
  /en/latest/live-player/: ./player/live.md
