root: ./

structure:
  summary: SUMMARY.md

redirects:
  /en/latest: ./README.md
  /en/latest/: ./README.md
  /en/latest/live-player: https://docs.trainyourears.com/player/live.md
  /en/latest/live-player/: https://docs.trainyourears.com/player/live.md
